// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkp4JrDlDr5scXY-Yk66Roml7FL6hjC94',
    appId: '1:1077560889481:web:62ab658e63276aa9073658',
    messagingSenderId: '1077560889481',
    projectId: 'borala-32c40',
    authDomain: 'borala-32c40.firebaseapp.com',
    storageBucket: 'borala-32c40.firebasestorage.app',
    measurementId: 'G-KG5LNL6JLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBif4ydDNyILf4BX_28hUyi80cWXM4GQ',
    appId: '1:1077560889481:android:2af7ef5c6c3e69bf073658',
    messagingSenderId: '1077560889481',
    projectId: 'borala-32c40',
    storageBucket: 'borala-32c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDYDN9VcLsB-Wnyp2x78w5v-Sge5_Ywo',
    appId: '1:1077560889481:ios:0bff6c550336c1e8073658',
    messagingSenderId: '1077560889481',
    projectId: 'borala-32c40',
    storageBucket: 'borala-32c40.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDYDN9VcLsB-Wnyp2x78w5v-Sge5_Ywo',
    appId: '1:1077560889481:ios:0bff6c550336c1e8073658',
    messagingSenderId: '1077560889481',
    projectId: 'borala-32c40',
    storageBucket: 'borala-32c40.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkp4JrDlDr5scXY-Yk66Roml7FL6hjC94',
    appId: '1:1077560889481:web:6b1e568790c119b1073658',
    messagingSenderId: '1077560889481',
    projectId: 'borala-32c40',
    authDomain: 'borala-32c40.firebaseapp.com',
    storageBucket: 'borala-32c40.firebasestorage.app',
    measurementId: 'G-9151CBN5X6',
  );
}
